project_id = "hgixhlcxvjvonmcxfvlc"

[functions.og-service]
verify_jwt = false

[functions.support-chatbot]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false
